// Generated by CoffeeScript 1.5.0
(function() {
  var current_page, open_for, reader, req;

  reader = new Reader;

  req = chrome.extension.connect({
    name: 'popup'
  });

  current_page = [];

  req.onMessage.addListener(function(res) {
    var ms;
    if (res.status) {
      ms = Date.now() - res.status.open_time;
      current_page.status = res.status;
      $('#type').text(reader.status_string(res.status.status));
      return $('#open-for').text("Time (m:s) " + (open_for(ms)));
    }
  });

  chrome.tabs.getSelected(null, function(tab) {
    req.postMessage({
      popup: {
        action: 'status',
        tab_id: tab.id
      }
    });
    return current_page.tab = tab;
  });

  $('.change_status').click(function(e) {
    var change;
    e.preventDefault();
    change = $(this).attr('id' === 'track') ? reader.status.user_init : reader.status.ignored;
    return req.postMessage({
      popup: {
        action: 'change_status',
        tab_id: current_page.tab.id,
        change_to: change
      }
    });
  });

  open_for = function(ms) {
    var time;
    time = new Date(ms);
    return "" + (time.getMinutes()) + ":" + (time.getSeconds());
  };

}).call(this);
